import type { Metadata } from 'next';
import './globals.scss';
import React from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <head>
        <link rel='icon' href='./logo.png' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <meta name='theme-color' content='#7ec6bf' />
        <meta name='Florencia Romero' content='Audiovisual translator and localization specialist' />
        <link rel='apple-touch-icon' href='./logo.png' />
        <title>Florencia Romero</title>
      </head>
      <body>{children}</body>
    </html>
  );
}
